# Generated by Django 4.2.7 on 2023-11-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
