# Generated by Django 4.2.7 on 2023-11-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberscategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to='social_net.profile'),
        ),
    ]
