# Generated by Django 4.2.7 on 2023-11-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('social_net', '0003_remove_category_subscribers_profile_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribersCategory',
            new_name='PostCategory',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='estimation',
            new_name='post_rating',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='categoryThrough',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='category_subscribers', to='social_net.category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(through='social_net.PostCategory', to='social_net.category'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='postThrough',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_net.post'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
