# Generated by Django 4.2.7 on 2023-11-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_net', '0004_rename_subscriberscategory_postcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_rating',
            new_name='_rating',
        ),
        migrations.AddField(
            model_name='post',
            name='estimation',
            field=models.IntegerField(default=0),
        ),
    ]
